### ISSUE TITLE
[Music] Create a features array with data from MIDI files

### ISSUE THREAD

**Issue by joeytepp** [QMIND-Team/QMIND-Music#34]
## Summary

In order to train our neural network, we will need a large two dimensional array storing the notes within each MIDI file

### Basic Example

A few things need to be done in the `music_library` file

- Remove the `convert_mp3_to_midi` function
- Change the `converter.parse` line to use the `midi_path` variable instead of being hardcoded to `'cut_to_the_feeling.mid'`
- Create a function `create_feature_array` that makes a 2D array out of the features of all the songs in the midi_songs folder ([This should be useful](https://github.com/QMIND-Team/QMIND-Music/blob/bd60548b5d9fa3ff25fe697b0b73491f6ceca59c/project/create_midi_files.py#L117))

### Motivation

To get training ⚙️

**Comment by sjcantor** [comment]
Closing this because issue is resolved now 🎈

**Comment by joeytepp** [comment]
Nice ✅
